---
name: $(major).$(minor).$(patch)-$(Build.SourceBranch)

# local variables 
variables:
- name: artifact_name
  value: 'app'
- name: major
  value: 1
- name: minor   
  value: 2
- name: patch
  value: $[counter(variables['minor'],1)]

trigger: 
  - main

# Add template repository
resources:
  repositories:
    - repository: templates
      type: git
      name: Epam-final-project/yaml-templates
      ref: artifact_task_change

# Create pipeline stages
stages:
  - stage: release
    displayName: Release
    pool: "vmss-epam-dev-westeurope-pool"
    jobs:
    - job: build
      displayName: build
      steps:
      - template: app-build.yml@templates
