---
galaxy_info:
  role_name: "msft"
  author: "Lean Delivery team <team@lean-delivery.com>"
  description: "Lean Delivery Microsoft software install"
  company: "Epam Systems"
  license: "Apache"
  min_ansible_version: "2.8"
  issue_tracker_url: "https://github.com/lean-delivery/ansible-role-msft/issues"
  platforms:
    - name: "Ubuntu"
      versions:
        - "bionic"
        - "xenial"
    - name: "Debian"
      versions:
        - "stretch"
        - "buster"
    - name: "EL"
      versions:
        - "7"
    - name: 'Amazon'
      versions:
        - '2017.12'
        - 'Candidate'

  galaxy_tags:
    - "development"
    - "system"
    - "container"
    - "packaging"
    - "msft"
    - "azure"
    - "az"
    - "pwsh"
    - "powershell"

dependencies: []
