name: "terraform deploy"
# Define pipeline parameters
parameters:
- name: agentPoolImage
  type: string
  default: 'windows-latest'
  values:
    - 'windows-latest'
    - 'windows-2022'
- name: artifact_version
  default: "*"
- name: target
  type: string
  default: 'apply'
  values:
    - 'apply'
    - 'destroy'
- name: environment
  type: string
  default: 'dev'
  values:
    - 'dev'
    - 'qa'
    - 'prd'

variables:
- name: artifact_name
  value: 'terraform'

# Add template repository
resources:
 repositories:
   - repository: templates
     type: git
     name: Epam-final-project/yaml-templates

# Create pipeline stages
stages:
- template: terraform-deploy.yml@templates
  parameters:
    artifact_version: ${{ parameters.artifact_version }}
    artifact_name: ${{ variables.artifact_name }}
    target: ${{ parameters.target }}
    environment: ${{ parameters.environment }}

